# Generated by Django 6.0.5 on 2026-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_userprofile_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incident',
            name='incidents_i_timesta_3ec689_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sos_phone',
            field=models.CharField(blank=True, default='', help_text='Emergency contact number for SOS alerts', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City or neighbourhood', max_length=100),
        ),
    ]
