# Generated by Django 6.0.5 on 2026-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('robbery', 'Robbery'), ('harassment', 'Harassment'), ('accident', 'Accident'), ('poor_lighting', 'Poor Lighting'), ('suspicious', 'Suspicious Activity'), ('flood', 'Flood'), ('fire', 'Fire'), ('assault', 'Assault'), ('vandalism', 'Vandalism'), ('kidnapping', 'Kidnapping'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
