# Generated by Django 6.0.5 on 2026-06-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidentmedia_savedincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('level', models.IntegerField(choices=[(1, 'Country'), (2, 'State'), (3, 'City'), (4, 'Local Area')], db_index=True)),
                ('slug', models.SlugField(max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_areas', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='incidents.area')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Structured area this incident belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.area'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['level', 'name'], name='incidents_a_level_c3ef6e_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['parent', 'level'], name='incidents_a_parent__36434b_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['slug'], name='incidents_a_slug_4bddf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'parent')},
        ),
    ]
