# Generated by Django 6.0.5 on 2026-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_verification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-created from a pin; awaiting admin audit.'),
        ),
    ]
