# Generated by Django 6.0.5 on 2026-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_area_needs_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmedia',
            name='file',
            field=models.FileField(upload_to='incident_media/'),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10),
        ),
    ]
