# Generated by Django 6.0.5 on 2026-06-22 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_alter_incidentmedia_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Fake or spam'), ('inappropriate', 'Inappropriate or harmful')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed — no action'), ('actioned', 'Reviewed — content removed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_raised', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('incident', 'flagged_by')},
            },
        ),
    ]
